## Case 5 - criação e seleção de coluna em DataFrame

Você recebeu uma pequena tabela de vendas de uma loja.

Crie um código com pandas que:

- importe o pandas como pd  

- crie um DataFrame com estas informações:  
  - produto: Notebook, Mouse, Teclado  
  - vendas: 30, 80, 45  

- mostre o DataFrame  

- mostre apenas a coluna produto

In [1]:
# Importando o pandas e criando um data frame
import pandas as pd

import pandas as pd

vendas = pd.DataFrame({
    'produto': ['Notebook', 'Mouse', 'Teclado'],
    'vendas': [30, 80, 45],
})

vendas

    produto  vendas
0  Notebook      30
1     Mouse      80
2   Teclado      45

In [3]:
# Mostrando apenas uma coluna
vendas[['produto']]

    produto
0  Notebook
1     Mouse
2   Teclado