## Case 45 — resumir após o merge

Use o resultado do outer merge do exercício anterior e faça um código que:

- crie os dois DataFrames  
- faça o outer merge  
- mostre:  
  - quantos pedidos existem por id_cliente

In [7]:
# Importando o pandas e criando um DataFrame
import pandas as pd

tb_1 = pd.DataFrame({
    'id_cliente': [1, 2, 3, 4 ],
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniela']
})

tb_2 = pd.DataFrame({
    'id_cliente': [1, 2, 2, 4, 5 ],
    'valor_pedido': [120, 250, 180, 300, 500]
})

df_junta = pd.merge(tb_1, tb_2, on='id_cliente', how='outer')

df_junta

   id_cliente     nome  valor_pedido
0           1      Ana         120.0
1           2    Bruno         250.0
2           2    Bruno         180.0
3           3   Carlos           NaN
4           4  Daniela         300.0
5           5      NaN         500.0

In [20]:
# Agrupa o resultado do merge por id_cliente pelo valor_pedido 
# Depois Adicionamos um nome personalizado para a funcao count
# Lembrando que count ignora valores null 
df_junta.groupby('id_cliente').agg(QtdeTransacao=('valor_pedido', 'count')).reset_index()

   id_cliente  QtdeTransacao
0           1              1
1           2              2
2           3              0
3           4              1
4           5              1