## Case 34 - identificação de valores faltantes

Crie um código com pandas usando estes dados:

- cliente: Ana, Bruno, Carlos, Daniela, Eva  
- cidade: SP, RJ, None, RJ, SP  
- valor_pedido: 120, 250, 80, None, 150  

Faça um código que:

- crie o DataFrame  
- mostre o DataFrame  
- mostre quais valores estão faltando

In [ ]:
# Importando o pandas e criando um data frame
import pandas as pd

# Criando um DataFrame com alguns valores faltantes
clientes = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'cidade': ['SP', 'RJ', None, 'RJ', 'SP'],
    'valor_pedido': [120, 250, 80, None, 150,]
})

clientes

   cliente cidade  valor_pedido
0      Ana     SP         120.0
1    Bruno     RJ         250.0
2   Carlos   None          80.0
3  Daniela     RJ           NaN
4      Eva     SP         150.0

In [ ]:
# Mostra com True e False, onde existem valores faltantes no DataFrame, onde True é onde falta 
clientes.isna()

   cliente  cidade  valor_pedido
0    False   False         False
1    False   False         False
2    False    True         False
3    False   False          True
4    False   False         False